web_app/lib/spo2_web/router.ex
defmodule Spo2Web.Router do
  use Spo2Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :login
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Spo2Web do
    pipe_through :browser

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/graph", GraphController, :index
    resources "/data", DataController
    get "/users/new", UserController, :new
    post "/users", UserController, :create
    get "/dashboard", DashboardController, :index

    # Sample Data
    get "spo2", DashboardController, :spo2
    get "hr", DashboardController, :heart_rate
    get "temperature", DashboardController, :skin_temp
  end

  # Other scopes may use custom stacks.
  # scope "/api", Spo2Web do
  #   pipe_through :api
  # end
end

web_app/lib/spo2_web/views/layout_view.ex
defmodule Spo2Web.LayoutView do
  use Spo2Web, :view
end

web_app/lib/spo2_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Spo2 Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 d-flex">
      <a class="navbar-brand" href="/">SpO2 Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <%= if logged_in?(@conn) do %>
            <li class="nav-item"><%= link "Dashboard", to: Routes.dashboard_path(@conn, :index), class: "nav-link"%></li>
            <li class="nav-item"><%= link "Sign out", to: Routes.session_path(@conn, :delete), class: "btn btn-outline-secondary" %></li>
            <% else %>
            <li class="nav-item"><%= link "Sign in", to: Routes.session_path(@conn, :new), class: "btn btn-outline-primary"%></li>
            <li class="nav-item"><%= link "Sign up", to: Routes.user_path(@conn, :new), class: "btn btn-outline-success"%></li>
            <% end %>
          </ul>
      </div>
    </nav>

    <main role="main" class="container-fluid">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>